### ISSUE TITLE
Request to view session data

### ISSUE THREAD

**Issue by DaMarkSta** [kulvind3r/GamingGaiden#16]
Would like an option in the stats to view individual session length, date played, and game played

**Comment by kulvind3r** [comment]
You can see the last session length in the log... last played date for every game is already tracked.

If you are requesting for a new feature where, for every game, every session's length and date of the session is recorded. Then i am not planning for that feature anytime soon.

It would really explode the statistics, for a game like Dota, Valorant people play 100s of session... a single game will generate huge number of records.

Driving philosophy behind the application is to keep it simple and high performing. 

Something that can be planned is the longest session ever played for a game. It's just one more record per game and might be a cool stat...

**Comment by kulvind3r** [comment]
Session length is currently printed as part of the logs... in the **_GamingGaiden.log_** file. The log file tracks everything internal to the application. It is used for finding bugs and stuff. 

The user shouldn't have to read through the file to find things. Session length is recorded for every gaming session but you will feel overwhelmed to find the line where it is and then copy pasting it out.

Since you asked so nicely... i went ahead and wrote a small program just for you to extract the session data from the Log.

1. Download the attached zip, extract the exe file inside it. 
2. Copy the exe file inside the Gaming Gaiden install directory. You can open it by clicking **_"Settings => Open Install Directory"_**
3. Then just run the exe, it will go through the **_GamingGaiden.log_** file , identify all gaming sessions and print them nicely for you in a file called **_"SessionData.txt"_** in same folder.
4. Run the exe again to update the session data file. 

Play few games a few times and the run the SessionData exe to get the session details printed. Have Fun!!

**WARNING:** The log file gets reset on every restart of the application. **So don't delete your **_"SessionData.txt"_** file ever.** You won't be able to get the old session data back. Keep backing it up regularly.

[SessionData.zip](https://github.com/user-attachments/files/16615867/SessionData.zip)

**Comment by DaMarkSta** [comment]
Thank you so much this is awesome!
