### ISSUE TITLE
[FR] - Easy Way To Import Games and Play Time from CSV

### ISSUE THREAD

**Issue by TheWireLord** [kulvind3r/GamingGaiden#17]
There are websites (Like this one: [Steam Library Filters](https://www.lorenzostanco.com/lab/steam/)) that will let you export your Games, Play Time, Last Played, and other stats to a CSV.

It would be really nice if GamingGaiden had the ability to Import From CSV to get the games and their related stats and import them into the Database GamingGaiden uses.

That way you wouldn't have to manually add the 100+ games you may have on Steam and their playtime and any time you launched that game via Steam, it would update the playtime in the GamingGaiden Database.

I'm not sure how it would manage which .exe to use or if that would just have to be selected manually either way, but this feature would be nice to have.

**Comment by kulvind3r** [comment]
The app's intent was to record active gaming hours you spent. i.e. starting from the day you started using the app it will record and report on your gaming life.

Although it functions as a pure time record keeper for games, i don't think just importing historical records here to keep them all in one place is in spirit of the application

I mean if you have played a steam game 3 years ago for 15 hrs. Only data you can import is total hours played and last played date. No session count, no daily stats etc from all those years ago. There will be no record of gaming activity.

I can understand that some users may want to keep all their gaming records in a single place i.e. Gaming Gaiden instead of keeping past ones in steam and current and future ones in Gaming Gaiden, but that's not the primary goal / value that app is trying to serve.

So not really a feature i am considering to add in app.

Next...

About current games being launched from Steam... you can record the data directly, why would we want to do it by importing CSV from other websites???

Just add the exe when you install the game to play it. You don't have to manually add your entire steam library upfront... just add the game you are playing... add the next one when you play it in future.

**Comment by TheWireLord** [comment]
Thanks for the reply!

Yeah I see what you mean with that not being the primary goal for this project.

I just meant that you would only have to import from the CSV one time to get the existing data from Steam so you wouldn't have to do it all manually for the many games a user may have.

After that, I was just trying to think of a way to also detect the .exe that those Steam games would use without doing them all manually. I may not have explained that clearly.

But I respect that this is not really a goal for this project.

Thanks again for the great tool!

**Comment by kulvind3r** [comment]
Thanks for your understanding... if you can extract and share your Steam CSV file with me, i can write a small utility to import the details from your CSV to your Gaming Gaiden DB. 

If the CSV won't have the EXE details for each game , i cannot do much as i can't find exact EXE for each game, i am not sure if it is even possible without installing every single game. But i can import rest of the details.

I am not adding it as a feature to the main app, but i can try and help you. I like coding so if it is not too complicated, it might be fun.

Share the CSV. :-) i am swamped with my job right now, but if it is simple enough i will try to share it back soon

**Comment by kulvind3r** [comment]
Closing the issue.
