### ISSUE TITLE
[Feature] Option to simultaneously record game time in multiple games

### ISSUE THREAD

**Issue by haloTT100** [kulvind3r/GamingGaiden#19]
Pretty self explanatory. I often play multiple games at the same time, this would be a great addition to track multiple games at once.

**Comment by kulvind3r** [comment]
Sorry it is not possible as of now. 

Once the app detects a game, it goes into a monitoring stage and detection stage is suspended. App remains in monitoring stage until the currently ongoing game is closed and only goes back to detection once the currently played game is closed and it's play time is recorded.

In order to monitor multiple games at same time, lots of core things in the app would have to be changed and complexity will increase significantly. It is also not a majority use case, majority of users just play one game at a time.

Maybe someday when i have more time at my hand i will look into how to make this happen.

**Comment by haloTT100** [comment]
I see, that's understandable. Thanks for considering it though.

**Comment by kulvind3r** [comment]
Thanks for being a polite requester. =) will give you a heads up if i do build this.
