### ISSUE TITLE
Some features and issues.

### ISSUE THREAD

**Issue by IgorDyx** [kulvind3r/GamingGaiden#23]
Hi. You created a very good app. Thank You.
I have some suggestions:
When I open 'about' option I don't see a current version of the app. Can you add it?
I would like to have an ability to adjust the size of 'editing game' window. It's too little.
I would like to have option to edit a date when I finished game. Because I keep forgetting set 'finished' checkbox and then after a week or two it shows a wrong date. I would like to set a correct date. Also it would allow to rearrange the order of games in UI
Please, separate playtime by years in UI. 1. I would like to have separation by years in unfinished games. For example total playtime 600 hours, in 2023 200hours, in 2024 400 hours. 2. Also total playtime needs to be separated by years too. New year - new separated list of games and unfinished old games copied to new list with old and new playtime. It would be appreciated. 
And the las one. Can you add a dark theme in UI? 
Thanks a lot.

**Comment by kulvind3r** [comment]
Lots of Suggestions here, let me address them one by one...

1. Version in about page. I can consider this. Although app version is present in the application executable. I will try to add it in About dialogue box  in one of the upcoming releases.

2. Making the application window size responsive i.e. able to increase or decrease size as required is a lot of work in Powershell and i am afraid i don't have the time to implement it as of now. Maybe someday in future.

The application is designed for 1080p screen and the size of all controls is standard for 1080p content. If you use a 4K or 1440p display and size is small , please use high DPI settings to make the window size large for your own use.

3. The games do not track "finished on" date. They just track "Last Played On". So there is no finished date to edit. There is only finished status. If you play a game marked as finished on another day, "Last Played On" date will be set to that day.  This is a time tracking application not a backlog diary application. So this is not a feature that is intended or planned.

4. You can see the hours played every year in the "Statistics => Time Spent Gaming" UI, if you switch to "Yearly Summary" total time for each year is shown at the bottom of page. In one of the upcoming releases another small Pie Chart will be present in the "Statistics => Life Time Summary" page which will show, playtime for each year. Here is a preview of the feature

![image](https://github.com/user-attachments/assets/863503b6-e5cf-4a0a-9e4f-240296efb4cc)

5. Application is meant to track total time played for a game. Separating total time by year is not something that is planed and won't be implemented.

6. I cannot implement a Dark UI since i am not a graphic designer and picking the right color combination is very hard for me and very time consuming. Please use a browser plugin or browser feature for dark mode, every browser these days have these

Lastly... 

It seems to me that you want to use the application for backlog tracking as the primary goal. That's not what i made the application for and it's feature will never be focused on backlog management. So please don't hope for the same. 

And i generally do not take feature requests as i have very limited time between my day job and Adult responsibilities. So please don't expect that... 

Sometimes some feature suggestions make sense and are doable with low effort so i would implement those, like your request for adding version to about page. But the app is meant for personal use and if it is useful for community they can use it too... App is not drive by user feature requests so much as you seem to feel in your post.

**Comment by kulvind3r** [comment]
One of the requested features has been implemented. Current version of the application ( i.e. release version ) will appear in about dialog from next release on wards.

**Comment by IgorDyx** [comment]
Understood. Thanks.

**Comment by IgorDyx** [comment]
Can you tell the name of the font you using in UI? Thanks.

**Comment by IgorDyx** [comment]
Can you telle me the name of the font you use in UI? Thanks.
![Screenshot 2024-12-12 092452](https://github.com/user-attachments/assets/51509026-ab93-4a7f-9b39-782e15b43e99)

**Comment by kulvind3r** [comment]
Monospace

```css
body {
  font-family: monospace;
  font-size: 14px;
  background-color: white;
}
```

**Comment by IgorDyx** [comment]
Hi one more time. I can see some numbers in graphs. Am I doing something wrong?
![Screenshot 2024-12-26 093317](https://github.com/user-attachments/assets/a54a4e3f-b5c4-421d-86dc-9e60dd58466c)

**Comment by kulvind3r** [comment]
No, nothing wrong on your end... this is a minor bug in the previous release. Upgrade to the latest version and then check again, the numbers will be visible again. 

I limited the scale to 8 hrs max in previous releases, didn't expect to game above 8 hrs in a day. 😄 but i was wrong... also that's a lot of gaming. If you don't mind me asking , how do you find so much time to play?

**Comment by IgorDyx** [comment]
Thanks.
I don't play SO MUCH. That's games I added from different platforms in August. Like from Steam Deck, so I added the whole time I played a game. Like 9 hours and more. But if tell the truth some times on weekends I can play more than 8 hours. For example in December I have two such days. (Was playing stalker 2) But it's exception for a game I highly anticipated. 
![Screenshot 2024-12-26 142624](https://github.com/user-attachments/assets/243979f7-4469-4bb5-ac40-5712de1447f7)

**Comment by kulvind3r** [comment]
Nice 😄 . This is the exact use for which i made the application. You can simply screenshot and share with your friends your play time over days, and even the list of games you played.

I was not playing at all for many months, tracking my hours motivated me to play at least an hour a day.

Happy to see the app being used for the exact purpose for which i made it, i hope it can get popular so that more people start sharing such stats. Maybe on a sub reddit 😛

**Comment by IgorDyx** [comment]
Hi. I updated Gaming Gaiden and have this err when add any game now. I add a game on December 28. It makes this err and shows December 29.
`spoiler` 
![Screenshot 2024-12-28 225233](https://github.com/user-attachments/assets/8ffd5b2c-c252-4c2e-8bf3-a3042a86007f)

**Comment by kulvind3r** [comment]
For the first issue, please share your log file. You can find it by clicking "settings => open install directory". 

For the 2nd issue, it is something to do with your system. Horizontal size of dialog box is smaller on your system. Did you resize it somehow? On my system it looks like this. 

![image](https://github.com/user-attachments/assets/f2a02093-af98-4bef-afb6-bf75494f0edf)

For the 3rd issue, do the icon look blurry for any new game or just the ones that you had already added before upgrade? and are these auto added icons from game's executable? because icon available from game's executable is very small and you should not use it in first place. This is why the `Search` and `Update` buttons have been provided in `Edit Game` .

**Comment by IgorDyx** [comment]
[GamingGaiden.log](https://github.com/user-attachments/files/18268806/GamingGaiden.log)

For the 2nd issue. Yes. I resize system because I have 1440p 27" monitor. Default scale is quite small also I use 120% text size. In previous version of GG it wasn't an issue. Can you fix it please.

3rd issue. Understood. Yes, blurry when I add new games in new version. But again. It wasn't a problem in previous. I had sometimes blurry icons from exe, but overall they were normal. Now they are all blurry. 
Buy the way. When I press "search" it searches a name of the game and the word "game" (For The King II Game) It better to add icon instead of Game word (For The King II icon) or open a website steamgriddb_com it contains all the icons for all the games.

**Comment by kulvind3r** [comment]
1. First issue was a genuine bug, thanks for reporting. Please update to [Latest Release](https://github.com/kulvind3r/GamingGaiden/releases/latest) which fixes it.

2. Increasing just the text size without increasing the overall length of dialog box will cause the text in UI to not render correctly. As i mentioned earlier , i cannot make the UI dialog boxes resizable easily. Have you tried using a high dpi setting  instead of increasing text size to 120%? like 125% in high dpi, it will scale everything to 125% not just text. See if you can use that for now, as resizable UI is not planned as of now.

3. The blurry icon will happen since the size of icons in WebUI has increased. If you use the auto generated icons they will look blurry. The auto generated icons are not something to be used long term, they are something quick to fill the empty space. I recommend you search and add proper thumbnail using google search.

4. The `game` suffix in the search term is added on purpose... there are emulation games which are english words for e.g. Playstation 2 has a game called `BLACK`. If i use the word `icon` google search will return results for random black colored icon and not the actual game. There are few other games with similar situation, hence the reason to use the word `game` in the search term

5. Using google image search is a decision to ensure that there is a high chance of finding the cover art for the game. Steam Grid DB won't have the cover art for retro emulation games. Also, the best cover art aspect ration is square. Which is also something added in the google image search query. It returns square aspect ration images which are quick and easy to use for a good looking UI instead of some random aspect ratio.

So as of now, i can only fix the first issue you are having. The rest are not bugs / problems, they are conscious design decisions taken for good reason.

**Comment by IgorDyx** [comment]
Understood. Thanks a lot! 👍🤝

**Comment by IgorDyx** [comment]
Hi again. Have a question. Why did you add that shadow to icons? Now if Icon is circle or just have transparency it still drops a square shadow...  Can you make it to drop a correct shadow or delete it. No shadow no problems. But that is my humble opinion. 
![Screenshot 2024-12-30 215643](https://github.com/user-attachments/assets/10faa952-a9ce-47e8-89f0-dcf6b5e0a9bc)

**Comment by kulvind3r** [comment]
I added shadows to icons because i like it.

Use the latest release. The shadows will be accurate to shape now.

**Comment by IgorDyx** [comment]
Excellent! Thanks!👍🤝

**Comment by IgorDyx** [comment]
Sometimes icons don't change in UI. I restarted GG and restarted even PC - doesn't help. Is this fixable?
![Screenshot 2025-01-05 092538](https://github.com/user-attachments/assets/0b5ef3f2-d04a-4e03-8cdf-506368c7c9d9)
![Screenshot 2025-01-05 092552](https://github.com/user-attachments/assets/76c6b70b-2a0c-4d2d-8efb-5ee1610b857f)

**Comment by kulvind3r** [comment]
Fixed in the latest release. Thanks for reporting.

**Comment by IgorDyx** [comment]
Hello again✌️😊. 
When I click on status in UI it shows either dropped games or playing. Could you do finished games first, then dropped and after that  playing games? Or add more options to rotation according all statuses?. Thanks. 
Also. I've dropped a lot of games and a huge part of them good ones. Not necessary shi_t like that emoji that placed on dropped games.😂 You can use more neutral emoji like shrugging🤷‍♂️
Thanks a lot for this app.

**Comment by kulvind3r** [comment]
1. "Status" sorts alphabetically and you can click again to sort alphabetically in reverse. "Finished" starts with an F, "Dropped" and "Playing" starts with D and P. So Finished games will always be in the middle of the two. This is not going to change. If you want to see just finished games , use the search bar, search for finished.

2. Can't change stuff just for you. You can change for yourself by replacing the **_"dropped.png"_** file in **_"C:\ProgramData\GamingGaiden\ui\resources\images"_** with any icon of your choice, just make sure the replacement file is also a png file and keep the name same i.e. **_"dropped.png"_**

**Comment by IgorDyx** [comment]
Got it. Thanks a lot

**Comment by IgorDyx** [comment]
Please answer if you can. How it counts? How it knows that i'm out? It shows up to 3 hours on some games. And I think it's incorrect.
