### ISSUE TITLE
FR: Support multiple machines (e.g. PC + SteamDeck)

### ISSUE THREAD

**Issue by rkj** [kulvind3r/GamingGaiden#7]
This could be done in some manual merge way or through some online sync (maybe Google Drive spreadsheet for simplicity / easy export / interop)

**Comment by kulvind3r** [comment]
All data is stored in a single DB file **_"GamingGaiden.db"_**.

For multiple windows PCs, you can use google drive sync application on your PC to keep a single Gaming Gaiden database synced on all PCs. Then just create a [symbolic link](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/mklink) from Gaming Gaiden install location to the actual Database file located in your google drive synced folder.

As for Steam Deck, if you have windows on steam deck you can use the above method.

If you use Steam OS ( default OS on deck ), then it is a Linux OS and the application doesn't work on linux. It is written in Powershell and uses Windows system apis to track time and other things.

I am not planning a linux build because i wrote this for my personal use and i don't use linux as my gaming system. Sharing it with everyone was something natural as it could benefit other windows users.

Community can build a linux version if they like. HTML, CSS and JS code is completely reusable on linux, only the powershell code would have to be re-written for linux OS. Say in Python or Go lang for e.g.

**Comment by kulvind3r** [comment]
Closing the issue as there has been no further response. Feature requested is not in scope of this project as explained above. Approach to support multiple windows systems has been shared.

**Comment by RoachArts** [comment]
Hi kulvind3r

I came across Gaming Gaiden A while back and I've been using it to track the time I spend on some of my software I use for work. It works great, but I'm hoping to set up a sync between multiple PCs. I thought I got it working by pointing it towards my one drive. It stores the backups folder and GamingGaiden.db file on one drive as well as the GamingGaiden.log file. I'm not sure if I made a mistake by storing that last one on one drive as well (GamingGaiden.log). 
I'm not a programmer and have very little understanding of the inner workings of programs.

I was wondering if you could confirm whether or not what I've done is correct, as it seems to be overriding the file on one drive with older versions instead of keeping the latest.

I'm posting here, cause it seemed like it was similar to my issue.
Many thanks and kind regards.

**Comment by kulvind3r** [comment]
GamingGaiden.log file should not be synced between multiple PCs. It is meant for tracking what the application is doing and so should be local to each instance of the application.

I don't know what your setup on each PC is, but i would give you a recommended way to use Gaming Gaiden across multiple PCs while keeping the Database synced. This is the way i would do it if i had to...

![Gaming Gaiden One Drive Sync](https://github.com/user-attachments/assets/a45edfb8-af43-48e7-84ac-ffea2b4cd5a5)


The install location shown in diagram is based on the latest release... so if you upgrade to latest release the application will be installed in that location and will run from there.

You just need to copy the GamingGaiden.db file from the PC which has the latest data to your OneDrive, and let it sync everywhere. Once it is synced, then create symlink to the file from the OneDrive folder in each pc to the Gaming Gaiden Install location.

To create a symlink you can use this tool , [Link Shell Extension](https://schinagl.priv.at/nt/hardlinkshellext/linkshellextension.html) it adds an option in right click menu of any file / folder for creating symlinks easily.

!! Exit GamingGaiden application if it is running. before doing the below steps.

After installing the above application, right click on the GamingGaiden.db file in your OneDrive  folder, click on **Pick Link Source** , then go to your GamingGaiden install directory , right click and choose **Drop As -> Symbolic Link**

Once you have created the symlink, don't forget to remove the GamingGaiden.db file in the install directory. Then start the application, it should start successfully and use the symbolic link to connect to the DB file directly in the OneDrive folder.

I hope this helps.

Glad to see that the application is helpful for people outside of gaming as well

**Comment by RoachArts** [comment]
Thank you so much for the clarification. I'll try and implement it as soon as possible. 
Amazing application by the way.
